name: learning_studio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2
 

dependencies:
  flutter:
    sdk: flutter
  dio:
  flutter_bloc:
  equatable:
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.3.0
  # path_provider: ^2.0.15
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  # skeletonizer: ^1.4.2
  cached_network_image: ^3.3.1
  get_it: ^8.0.0
  # async: ^2.11.0
  easy_localization: ^3.0.7
  # reactive_forms: ^17.0.1
  go_router: ^14.2.8
  animate_do: ^3.3.4
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.1
  pinput: ^5.0.0
  flutter_slidable: ^3.1.1
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  url_launcher: ^6.1.10
  flutter_html:
    git:
      url: https://github.com/AgMarwanAg/flutter_html.git
  icons_launcher: ^3.0.0
  toastification: ^2.3.0
  share_plus: ^10.1.2
  flutter_advanced_drawer: ^1.3.7
  # animated_snack_bar: ^0.4.0
  firebase_remote_config: ^5.2.0
      
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Cocon
      fonts:
        - asset: assets/fonts/cocon-next-arabic.ttf
          weight: 300
        - asset: assets/fonts/CoconNextArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/CoconNextArabic-Bold.ttf
          weight: 500
          

  

